add_newline = false
command_timeout = 1000

[character]
success_symbol = "[√>](bold green)"
error_symbol = "[√>](bold red)"

[status]
disabled = false
format = '[\[$status - $common_meaning\]](yellow) '

[time]
disabled = false
style = "bold #00d7ff"

[directory]
truncation_length = 10
truncate_to_repo = false
style = "bold #5fafff"

format = "[$time:$path]($style) [$read_only]($read_only_style)"
