
add_newline = false

[character]
success_symbol = "[√ >](bold green)"
error_symbol = "[√ >](bold red)"

[status]
disabled = false
format = '[\[$status - $common_meaning\]](green) '

[time]
disabled = false 
style = "cyan"

[directory]
truncation_length = 10
truncate_to_repo = false
style = "yellow"

[custom.uptime]
command = "uptime.sh"
when = "true"
# format = "[$symbol($output)](green)"

format = "[$time:$path]($style) [$read_only]($read_only_style) "
