add_newline = false
command_timeout = 1000
[character]
success_symbol = "[√>](bold yellow)"
error_symbol = "[√>](bold red)"

[status]
disabled = false
format = '[\[$status - $common_meaning\]](yellow) '

[time]
disabled = false 
style = "yellow"
#STARSHIP_TIME_PREFIX=""

[directory]
truncation_length = 10
truncate_to_repo = false
style = "yellow"

[custom.uptime]
command = "uptime.sh"
when = "true"
# format = "[$symbol($output)](green)"

format = "[$time:$path]($style) [$read_only]($read_only_style)"
